# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("uteis/icone.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(118, 118, 118);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pgInicial = QtWidgets.QWidget()
        self.pgInicial.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pgInicial.setObjectName("pgInicial")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pgInicial)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self._Vertical = QtWidgets.QFrame(self.pgInicial)
        self._Vertical.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._Vertical.setFrameShadow(QtWidgets.QFrame.Raised)
        self._Vertical.setObjectName("_Vertical")
        self.gridLayout_5 = QtWidgets.QGridLayout(self._Vertical)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 1)
        self._Horizontal = QtWidgets.QFrame(self._Vertical)
        self._Horizontal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._Horizontal.setFrameShadow(QtWidgets.QFrame.Raised)
        self._Horizontal.setObjectName("_Horizontal")
        self.gridLayout_3 = QtWidgets.QGridLayout(self._Horizontal)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 1)
        self._inicialBaixo = QtWidgets.QFrame(self._Horizontal)
        self._inicialBaixo.setMinimumSize(QtCore.QSize(500, 150))
        self._inicialBaixo.setMaximumSize(QtCore.QSize(500, 150))
        self._inicialBaixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._inicialBaixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self._inicialBaixo.setObjectName("_inicialBaixo")
        self.inputCaminho = QtWidgets.QLineEdit(self._inicialBaixo)
        self.inputCaminho.setGeometry(QtCore.QRect(100, 30, 300, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputCaminho.sizePolicy().hasHeightForWidth())
        self.inputCaminho.setSizePolicy(sizePolicy)
        self.inputCaminho.setMinimumSize(QtCore.QSize(300, 30))
        self.inputCaminho.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputCaminho.setFont(font)
        self.inputCaminho.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.inputCaminho.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid white;\n"
"border-radius: 8px;")
        self.inputCaminho.setInputMask("")
        self.inputCaminho.setText("")
        self.inputCaminho.setMaxLength(500)
        self.inputCaminho.setAlignment(QtCore.Qt.AlignCenter)
        self.inputCaminho.setObjectName("inputCaminho")
        self.btnCaminho = QtWidgets.QPushButton(self._inicialBaixo)
        self.btnCaminho.setGeometry(QtCore.QRect(200, 76, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCaminho.sizePolicy().hasHeightForWidth())
        self.btnCaminho.setSizePolicy(sizePolicy)
        self.btnCaminho.setMinimumSize(QtCore.QSize(100, 30))
        self.btnCaminho.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnCaminho.setFont(font)
        self.btnCaminho.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCaminho.setStyleSheet("QPushButton {\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.btnCaminho.setObjectName("btnCaminho")
        self.gridLayout_3.addWidget(self._inicialBaixo, 2, 0, 1, 1)
        self._inicialCima = QtWidgets.QFrame(self._Horizontal)
        self._inicialCima.setMinimumSize(QtCore.QSize(500, 150))
        self._inicialCima.setMaximumSize(QtCore.QSize(500, 150))
        self._inicialCima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._inicialCima.setFrameShadow(QtWidgets.QFrame.Raised)
        self._inicialCima.setObjectName("_inicialCima")
        self._titulo = QtWidgets.QLabel(self._inicialCima)
        self._titulo.setGeometry(QtCore.QRect(100, 80, 300, 50))
        self._titulo.setMinimumSize(QtCore.QSize(300, 50))
        self._titulo.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self._titulo.setFont(font)
        self._titulo.setStyleSheet("color: white;\n"
"")
        self._titulo.setAlignment(QtCore.Qt.AlignCenter)
        self._titulo.setObjectName("_titulo")
        self._icone = QtWidgets.QLabel(self._inicialCima)
        self._icone.setGeometry(QtCore.QRect(200, 20, 60, 60))
        self._icone.setMinimumSize(QtCore.QSize(60, 60))
        self._icone.setMaximumSize(QtCore.QSize(60, 60))
        self._icone.setText("")
        self._icone.setPixmap(QtGui.QPixmap("uteis/lupa.png"))
        self._icone.setScaledContents(True)
        self._icone.setAlignment(QtCore.Qt.AlignCenter)
        self._icone.setObjectName("_icone")
        self.gridLayout_3.addWidget(self._inicialCima, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self._Horizontal, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self._Vertical)
        self.stackedWidget.addWidget(self.pgInicial)
        self.pgRedimensionar = QtWidgets.QWidget()
        self.pgRedimensionar.setObjectName("pgRedimensionar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pgRedimensionar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self._cima = QtWidgets.QFrame(self.pgRedimensionar)
        self._cima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._cima.setFrameShadow(QtWidgets.QFrame.Raised)
        self._cima.setObjectName("_cima")
        self.gridLayout_4 = QtWidgets.QGridLayout(self._cima)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self._cima)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 478, 172))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.img = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img.setText("")
        self.img.setObjectName("img")
        self.gridLayout_2.addWidget(self.img, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self._cima)
        self._baixo = QtWidgets.QFrame(self.pgRedimensionar)
        self._baixo.setMinimumSize(QtCore.QSize(500, 100))
        self._baixo.setMaximumSize(QtCore.QSize(16777215, 400))
        self._baixo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._baixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._baixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self._baixo.setObjectName("_baixo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self._baixo)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self._baixoSuperior = QtWidgets.QFrame(self._baixo)
        self._baixoSuperior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._baixoSuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self._baixoSuperior.setObjectName("_baixoSuperior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self._baixoSuperior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._width = QtWidgets.QLabel(self._baixoSuperior)
        self._width.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self._width.setFont(font)
        self._width.setStyleSheet("color: rgb(212, 212, 212);")
        self._width.setObjectName("_width")
        self.horizontalLayout_2.addWidget(self._width)
        self.inputWidth = QtWidgets.QLineEdit(self._baixoSuperior)
        self.inputWidth.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputWidth.setFont(font)
        self.inputWidth.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.inputWidth.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid white;\n"
"border-radius: 8px;")
        self.inputWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.inputWidth.setPlaceholderText("")
        self.inputWidth.setObjectName("inputWidth")
        self.horizontalLayout_2.addWidget(self.inputWidth)
        self._height = QtWidgets.QLabel(self._baixoSuperior)
        self._height.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self._height.setFont(font)
        self._height.setStyleSheet("color: rgb(212, 212, 212);")
        self._height.setObjectName("_height")
        self.horizontalLayout_2.addWidget(self._height)
        self.inputHeight = QtWidgets.QLineEdit(self._baixoSuperior)
        self.inputHeight.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputHeight.setFont(font)
        self.inputHeight.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.inputHeight.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid white;\n"
"border-radius: 8px;")
        self.inputHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.inputHeight.setPlaceholderText("")
        self.inputHeight.setObjectName("inputHeight")
        self.horizontalLayout_2.addWidget(self.inputHeight)
        self.btnAjust = QtWidgets.QCheckBox(self._baixoSuperior)
        self.btnAjust.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAjust.setStyleSheet("color: white;")
        self.btnAjust.setObjectName("btnAjust")
        self.horizontalLayout_2.addWidget(self.btnAjust)
        self.verticalLayout_3.addWidget(self._baixoSuperior)
        self._baixoInferior = QtWidgets.QFrame(self._baixo)
        self._baixoInferior.setMaximumSize(QtCore.QSize(16777215, 200))
        self._baixoInferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._baixoInferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self._baixoInferior.setObjectName("_baixoInferior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._baixoInferior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.btnRedimensionar = QtWidgets.QPushButton(self._baixoInferior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRedimensionar.sizePolicy().hasHeightForWidth())
        self.btnRedimensionar.setSizePolicy(sizePolicy)
        self.btnRedimensionar.setMinimumSize(QtCore.QSize(100, 30))
        self.btnRedimensionar.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.btnRedimensionar.setFont(font)
        self.btnRedimensionar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRedimensionar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnRedimensionar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.btnRedimensionar.setFlat(False)
        self.btnRedimensionar.setObjectName("btnRedimensionar")
        self.horizontalLayout.addWidget(self.btnRedimensionar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btnSalvar = QtWidgets.QPushButton(self._baixoInferior)
        self.btnSalvar.setMinimumSize(QtCore.QSize(80, 30))
        self.btnSalvar.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.btnSalvar.setFont(font)
        self.btnSalvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSalvar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.btnSalvar.setObjectName("btnSalvar")
        self.horizontalLayout.addWidget(self.btnSalvar)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.btnVoltar = QtWidgets.QPushButton(self._baixoInferior)
        self.btnVoltar.setMinimumSize(QtCore.QSize(70, 30))
        self.btnVoltar.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.btnVoltar.setFont(font)
        self.btnVoltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVoltar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 100, 100);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.btnVoltar.setObjectName("btnVoltar")
        self.horizontalLayout.addWidget(self.btnVoltar)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_3.addWidget(self._baixoInferior)
        self.verticalLayout_2.addWidget(self._baixo)
        self.stackedWidget.addWidget(self.pgRedimensionar)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Redimensionador"))
        self.inputCaminho.setPlaceholderText(_translate("MainWindow", "Insira o caminho:"))
        self.btnCaminho.setText(_translate("MainWindow", "Localizar"))
        self._titulo.setText(_translate("MainWindow", "Redimensionador de imagens"))
        self._width.setText(_translate("MainWindow", "Width:"))
        self.inputWidth.setText(_translate("MainWindow", "Largura:"))
        self._height.setText(_translate("MainWindow", "Height:"))
        self.inputHeight.setText(_translate("MainWindow", "Altura:"))
        self.btnAjust.setText(_translate("MainWindow", "AJUST"))
        self.btnRedimensionar.setText(_translate("MainWindow", "Redimensionar"))
        self.btnSalvar.setText(_translate("MainWindow", "Salvar"))
        self.btnVoltar.setText(_translate("MainWindow", "Voltar"))
